"use client";

import * as React from "react";
import { Search, Plus, MoreHorizontal } from "lucide-react";
import { segmentSeed, tagSeed, crmCampaigns } from "@/data/crm";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RecordFormModal } from "@/components/dashboard/crud";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const content = { segments: { title: "Segments", description: "Build focused audiences from your CRM data.", entity: "segment" }, tags: { title: "Tags", description: "Label leads so your team can act on intent and context.", entity: "tag" }, tasks: { title: "Tasks", description: "Keep follow-ups visible and moving across the team.", entity: "task" }, "data-table": { title: "Data Tables", description: "Explore and edit the structured data behind your workspace.", entity: "table" }, scripts: { title: "Scripts", description: "Give reps and AI agents a consistent conversation path.", entity: "script" }, templates: { title: "Templates", description: "Reusable messages for fast, thoughtful outreach.", entity: "template" } } as const;
export function ResourceWorkspace({ type }: { type: keyof typeof content }) { const info = content[type]; const [open, setOpen] = React.useState(false); const items = type === "segments" ? segmentSeed : type === "tags" ? tagSeed : crmCampaigns.map((name, index) => ({ id: String(index), name, description: `Reusable ${info.entity} workspace item`, leads: 0 })); return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">CRM resources</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight">{info.title}</h1><p className="mt-1 text-sm text-muted-foreground">{info.description}</p></div><Button onClick={() => setOpen(true)}><Plus data-icon="inline-start" /> New {info.entity}</Button></div><div className="flex items-center gap-3"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder={`Search ${info.title.toLowerCase()}...`} /></div><Badge variant="secondary">{items.length} records</Badge></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.id} className="transition hover:-translate-y-0.5 hover:shadow-md"><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle className="text-base">{item.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{"description" in item ? item.description : "Reusable workspace resource"}</p></div><Button variant="ghost" size="icon" aria-label={`More actions for ${item.name}`}><MoreHorizontal /></Button></CardHeader><CardContent className="flex items-center justify-between text-xs text-muted-foreground"><span>{"leadCount" in item ? `${item.leadCount} leads` : "Ready to use"}</span><Badge variant="outline">Active</Badge></CardContent></Card>)}</div><RecordFormModal open={open} onOpenChange={setOpen} title={`New ${info.entity}`} description={`Create a ${info.entity} for your team.`} mode="create" onSubmit={() => { toast.success(`${info.entity} created`); setOpen(false); }}><div className="flex flex-col gap-2"><Label htmlFor="resource-name">Name</Label><Input id="resource-name" placeholder={`${info.entity} name`} /></div><div className="flex flex-col gap-2"><Label htmlFor="resource-description">Description</Label><Textarea id="resource-description" placeholder="Describe how your team should use this resource" /></div></RecordFormModal></div>; }
